### ISSUE TITLE
[bug] stashdb-rm not removing studios on homepage

### ISSUE THREAD

**Issue by SpLLash4K** [feederbox826/userscripts#2]
Hi, looks like the stashdb-rm userscript isn't removing studios for me. Still seeing studios that are recorded in the json on various pages throughout stashdb

**Comment by feederbox826** [comment]
just to confirm, which studios and did you uncomment the applicable list(s)?

**Comment by SpLLash4K** [comment]
Tried both of these:

- https://feederbox.cc/uscript/static/stashdb-rm/gay-studios.json (was throwing CORS an error in dev console)
  - <img width="565" alt="image" src="https://github.com/user-attachments/assets/29a8bd73-7f23-4928-960c-ba8564544f52" />
- https://raw.githubusercontent.com/feederbox826/userscripts/refs/heads/main/static/stashdb-rm/gay-studios.json
  - No error with this one but not working either, this seems to be where the first link was redirecting so I tried it directly

**Comment by feederbox826** [comment]
TIL CORS looks at redirect as well. Should be fixed now
